[package]
name = "assignment_BankingTxnProcessor"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }